# To use H2 create schema.sql and data.sql files
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  batch:
    initialize-schema: always
    job:
      enabled: false # Prevent the job to run on app's start